# Generated by Django 5.1.6 on 2025-02-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=255)),
                ('hospital_location', models.TextField()),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('hospital_contact', models.CharField(max_length=20)),
                ('hospital_code', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
